### ISSUE TITLE
Segmentation fault when robots with Lua controllers are selected

### ISSUE THREAD

**Issue by alanmillard** [ilpincy/argos3#47] opened 2017-11-01 15:18 UTC
Shift+clicking on a robot should select the robot and display its internal variable values in the Lua editor, but this results in a segmentation fault. I cannot reproduce this problem on my Mac, but it happens every time under Linux. I'm running the latest version of ARGoS (3.0.0-beta48).

The attached file contains the .argos configuration file, .lua controller, and an example core dump.

[core_dump.zip](https://github.com/ilpincy/argos3/files/1434575/core_dump.zip)

**Comment by ilpincy** [comment] 2017-11-01 15:42
I'll look into it. Is this related to the selection bug that is already open? That is due to the Intel driver managing badly multiple graphics cards.

**Comment by allsey87** [comment] 2017-11-01 15:55
@alanmillard could you check if you have `lua_editor="true"` set inside the OpenGL tag?

**Comment by allsey87** [comment] 2017-11-01 15:59
Never mind, I see you do have this variable set from core_dump/obstacle_avoidance.argos. This indeed seems like it may be a duplicate of #40 then.

**Comment by alanmillard** [comment] 2017-11-01 16:47
This certainly looks like it may be a duplicate of #40.

Let me know if there are any tests that I can run for you on this system to provide further information that may be of use.

**Comment by ilpincy** [comment] 2017-11-01 17:29
Try disabling the Intel video card. Unfortunately there isn't much I can do :(

**Closed by ilpincy** 2017-11-01 17:29 UTC
Labels: bug, duplicate

**Comment by allsey87** [comment] 2017-11-02 14:16
@ilpincy is it possible to propose a series of tests that we can use to probe this issue a little bit deeper? It would be good if we can collaborate and get #40 resolved at some point.

From my testing, it seems that the entities are being drawn in the selection buffer such that they are offset from what is being drawn in the display buffer. This corruption becomes apparent when the `makeCurrent()` and `doneCurrent()` lines are removed. So at a best guess on my end, the segfault is a result of calling the `makeCurrent()` and `doneCurrent()` functions when drawing incorrectly inside the selection buffer...

**Comment by ilpincy** [comment] 2017-11-04 06:21
I doubt the bug is due to code in ARGoS. If so, it would happen on other Linux boxes, other drivers, etc. It only happens with a specific driver on machines that have multiple graphics cards.

**Comment by beltrame** [comment] 2017-11-04 07:06
Actually it happens on any machine with Intel cards, whether they have multiple cards or not. It happens on mine and I don't have a multi card system.

On November 4, 2017 7:21:37 AM GMT+01:00, Carlo Pinciroli <notifications@github.com> wrote:
>I doubt the bug is due to code in ARGoS. If so, it would happen on
>other Linux boxes, other drivers, etc. It only happens with a specific
>driver on machines that have multiple graphics cards.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ilpincy/argos3/issues/47#issuecomment-341875507

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ilpincy** [comment] 2017-11-04 07:09
Good to know, it doesn't happen on my old laptop which also has a single Intel card. It's still driver specific though.
